workers:
  - period: 10s
    job:
      name: http-requestor
      code: |
        package main

        import (
          "github.com/topfreegames/go-etl/processors"
          "github.com/topfreegames/go-etl/models"
        )

        type etl string

        func (e etl) Extract() models.DataProcessor {
          return processors.NewHTTPRequestor("GET", "http://localhost:8080")
        }

        func (e etl) Transform() models.DataProcessor {
          return &processors.Logger{}
        }

        func (e etl) Load() models.DataProcessor {
          return &processors.Null{}
        }

        // ETL is the exported symbol of this plugin
        var ETL etl
  - schedule:
      hour: 17
      minute: 29
    job:
      name: hello-world
